The csv files are generated by the [VAE_3.0_spike_statistics.ipynb]

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
import re

# 0: The Statistics
We will use the statistics as a user

In [6]:
mean = 0.16
median = 0.2
std = 0.1
min = 0.02
max = 4
gradient = 0.18
statistics_df = pd.DataFrame({'mean': [mean], 'median': [median], 'std': [std], 'min': [min], 'max': [max], 'gradient': [gradient]})
X = [mean, median, std, min, max, gradient]
X = statistics_df.values
kmoid_cluster = joblib.load('../Data_preprocess/kmedoids_model.joblib')
cluster = kmoid_cluster.predict(X)[0]
statistics_df['kmedoid_clusters'] = cluster
print(statistics_df)

   mean  median  std   min  max  gradient  kmedoid_clusters
0  0.16     0.2  0.1  0.02    4      0.18                 6

# 1. Number of spikes for a day

In [7]:
def generate_random_spike_count(cluster, month):
    spike_num_prob_df = pd.read_csv('../../Data_processed/Spike_count_cluster_month.csv')
    temp_df = spike_num_prob_df[spike_num_prob_df['kmedoid_clusters'] == cluster]
    selected_spike_count = np.random.choice(temp_df['spike_count'], p=temp_df[f'month_{month}'])
    return selected_spike_count
    

spike_count = generate_random_spike_count(0, 2)
print(spike_count)

4.0

In [12]:
spike_num_prob_df = pd.read_csv('../../Data_processed/Spike_count_cluster_month.csv')
spike_num_prob_df

,kmedoid_clusters,spike_count,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12
0,0,1,0.403600,0.409409,0.425867,0.487109,0.521268,0.551985,0.609058,0.603919,0.544037,0.510842,0.449420,0.423755
1,0,2,0.320185,0.321335,0.308708,0.304457,0.306922,0.297936,0.265801,0.270102,0.287942,0.296274,0.310558,0.309031
2,0,3,0.186209,0.181510,0.182237,0.148619,0.126415,0.110893,0.097207,0.094194,0.120183,0.138133,0.162521,0.178106
3,0,4,0.090006,0.087746,0.083188,0.059814,0.045395,0.039185,0.027935,0.031785,0.047837,0.054750,0.077501,0.089108
4,1,1,0.442430,0.464061,0.482127,0.548642,0.582584,0.605536,0.644160,0.629086,0.593736,0.557135,0.500151,0.470179
5,1,2,0.327955,0.317196,0.313598,0.295190,0.283810,0.276905,0.255877,0.262843,0.283833,0.292666,0.318702,0.312810
6,1,3,0.162948,0.154934,0.146110,0.118386,0.102371,0.090941,0.076641,0.081543,0.092624,0.111771,0.130026,0.153442
7,1,4,0.066667,0.063809,0.058166,0.037781,0.031235,0.026617,0.023321,0.026527,0.029807,0.038428,0.051122,0.063570
8,2,1,0.449123,0.451854,0.473188,0.526164,0.567959,0.595081,0.636706,0.629845,0.574485,0.548736,0.480089,0.456102
9,2,2,0.312523,0.311150,0.301872,0.287234,0.288128,0.265104,0.258163,0.249471,0.278905,0.280578,0.299709,0.305575
10,2,3,0.160678,0.167595,0.154120,0.135854,0.108161,0.108121,0.080553,0.090381,0.106182,0.124332,0.153462,0.162170
11,2,4,0.077677,0.069401,0.070819,0.050748,0.035752,0.031694,0.024578,0.030303,0.040428,0.046354,0.066741,0.076154
12,3,1,0.413678,0.438146,0.447233,0.521850,0.573825,0.598955,0.640587,0.621574,0.590628,0.542251,0.469406,0.440452
13,3,2,0.338089,0.333629,0.332467,0.312847,0.295057,0.283716,0.269231,0.274939,0.285428,0.304934,0.328867,0.322712
14,3,3,0.172579,0.163493,0.160386,0.122375,0.100486,0.091561,0.072597,0.082510,0.096072,0.116025,0.146568,0.168060
15,3,4,0.075654,0.064733,0.059914,0.042928,0.030632,0.025768,0.017585,0.020977,0.027872,0.036790,0.055159,0.068776
16,4,1,0.439291,0.454390,0.467431,0.512399,0.550939,0.575302,0.612216,0.603498,0.566993,0.536982,0.493111,0.461687
17,4,2,0.322142,0.311498,0.305051,0.303110,0.293550,0.277211,0.271449,0.275720,0.284249,0.293642,0.301955,0.311659
18,4,3,0.168886,0.164537,0.160456,0.134384,0.118307,0.111300,0.089914,0.090947,0.111310,0.120861,0.148090,0.155830
19,4,4,0.069682,0.069574,0.067062,0.050107,0.037204,0.036187,0.026422,0.029835,0.037448,0.048515,0.056843,0.070824
20,5,1,0.375181,0.380679,0.395091,0.453490,0.515521,0.550804,0.618411,0.580804,0.538351,0.500815,0.428012,0.393979
21,5,2,0.323500,0.322472,0.313935,0.319468,0.311046,0.294398,0.259306,0.277319,0.291050,0.302118,0.321780,0.311169
22,5,3,0.199768,0.203029,0.193179,0.162741,0.131069,0.114661,0.094071,0.107024,0.120642,0.141840,0.171305,0.192951
23,5,4,0.101551,0.093819,0.097794,0.064300,0.042363,0.040136,0.028211,0.034853,0.049957,0.055227,0.078904,0.101901
24,6,1,0.370842,0.372813,0.389802,0.470203,0.527715,0.564259,0.634777,0.610210,0.536831,0.508263,0.424382,0.382082
25,6,2,0.320452,0.324529,0.318985,0.317860,0.308614,0.293740,0.255669,0.265057,0.294545,0.299326,0.325033,0.314932
26,6,3,0.204819,0.200791,0.189617,0.145712,0.120506,0.105511,0.079618,0.092418,0.122182,0.140523,0.171887,0.196758
27,6,4,0.103887,0.101867,0.101597,0.066225,0.043165,0.036490,0.029936,0.032315,0.046442,0.051888,0.078698,0.106229
28,7,1,0.376727,0.378535,0.392576,0.451518,0.500556,0.531605,0.602905,0.603351,0.530152,0.501308,0.440081,0.405377
29,7,2,0.326584,0.333421,0.331762,0.327558,0.321061,0.313931,0.273312,0.271898,0.304697,0.313782,0.325254,0.328698
30,7,3,0.199857,0.199263,0.191875,0.156191,0.134760,0.119145,0.097376,0.094227,0.123030,0.137133,0.170210,0.178255
31,7,4,0.096832,0.088781,0.083787,0.064733,0.043623,0.035319,0.026407,0.030524,0.042121,0.047776,0.064455,0.087671
32,8,1,0.396210,0.380997,0.395317,0.502297,0.576486,0.620293,0.666034,0.657129,0.570482,0.556748,0.463499,0.415419
33,8,2,0.310886,0.318272,0.317314,0.296637,0.279392,0.257233,0.234345,0.238203,0.278903,0.278918,0.305582,0.301442
34,8,3,0.195269,0.189369,0.191128,0.137946,0.108216,0.088585,0.071869,0.080321,0.112204,0.119092,0.161380,0.182612
35,8,4,0.097635,0.111362,0.096242,0.063120,0.035905,0.033888,0.027751,0.024347,0.038411,0.045243,0.069539,0.100527
36,9,1,0.406304,0.429922,0.434554,0.561404,0.635703,0.660903,0.676974,0.702341,0.627407,0.625176,0.512527,0.467003
37,9,2,0.292746,0.293311,0.298180,0.256433,0.229740,0.222863,0.214474,0.200669,0.240036,0.235232,0.275853,0.286398
38,9,3,0.198402,0.174663,0.176277,0.124854,0.098242,0.088377,0.073684,0.065552,0.101657,0.096343,0.147122,0.171033
39,9,4,0.102547,0.102104,0.090989,0.057310,0.036315,0.027858,0.034868,0.031438,0.030900,0.043249,0.064499,0.075567

# 2. When the spike(s) occur

In [5]:
# Function to manually parse and format the time_quad string
def parse_and_format_time(time_quad_str):
    # Extract all time occurrences using regex
    times = re.findall(r'\d+, \d+', time_quad_str)
    # Convert each found time into a formatted string
    formatted_times = [f"{int(hour):02d}:{int(minute):02d}:00" for hour, minute in (time.split(', ') for time in times)]
    return tuple(formatted_times)

In [6]:
def get_spike_time(cluster, spike_count):
    spike_time_prob_df = pd.read_csv(f'../../Data_processed/statistics/{spike_count}spike_time_pair.csv')
    if spike_count == 1:
        pass
    else:
        spike_time_prob_df['time_pairs'] = spike_time_prob_df['time_pairs'].apply(parse_and_format_time)

    spike_time_prob_df = spike_time_prob_df[spike_time_prob_df['clusters'] == cluster]
    
    spike_time_prob_df['probability'] /= spike_time_prob_df['probability'].sum()

    selected_time = np.random.choice(spike_time_prob_df['time_pairs'], p=spike_time_prob_df['probability'])

    return selected_time

spike_time = get_spike_time(cluster, spike_count)
print(spike_time)

('13:30:00', '15:00:00')

In [14]:
spike_time_prob_df = pd.read_csv(f'../../Data_processed/statistics/{2}spike_time_pair.csv')
spike_time_prob_df

                                           time_pairs  probability  clusters
0         (datetime.time(0, 0), datetime.time(0, 30))     0.000076         6
1          (datetime.time(0, 0), datetime.time(1, 0))     0.000405         6
2         (datetime.time(0, 0), datetime.time(1, 30))     0.000380         6
3          (datetime.time(0, 0), datetime.time(2, 0))     0.000076         6
4         (datetime.time(0, 0), datetime.time(2, 30))     0.000076         6
...                                               ...          ...       ...
10199    (datetime.time(22, 0), datetime.time(23, 0))     0.001170         0
10200   (datetime.time(22, 0), datetime.time(23, 30))     0.001040         0
10201   (datetime.time(22, 30), datetime.time(23, 0))     0.000032         0
10202  (datetime.time(22, 30), datetime.time(23, 30))     0.001105         0
10203   (datetime.time(23, 0), datetime.time(23, 30))     0.000032         0

[10204 rows x 3 columns]

# 3. What types are the spikes?

In [7]:
def get_spike_type(cluster, spike_count):
    spike_type_prob_df = pd.read_csv(f'../../Data_processed/statistics/{spike_count}spike_type_prob.csv')
    spike_type_prob_df = spike_type_prob_df[spike_type_prob_df['clusters'] == cluster]
    spike_type_prob_df['probability'] /= spike_type_prob_df['probability'].sum()

    selected_spike_type = []
    for i in range(spike_count):
        selected_spike_type.append(np.random.choice(spike_type_prob_df['spike_type'], p=spike_type_prob_df['probability']))
    
    return selected_spike_type


spike_type = get_spike_type(cluster, spike_count)
print(spike_type)

[2, 2]

In [15]:
spike_type_prob_df = pd.read_csv(f'../../Data_processed/statistics/{1}spike_type_prob.csv')
spike_type_prob_df

    clusters  spike_type  probability
0          6           2     0.500818
1          6           3     0.499182
2          9           2     0.548102
3          9           3     0.451898
4          2           2     0.356547
5          2           3     0.643453
6          5           2     0.463800
7          5           3     0.536200
8          4           2     0.365910
9          4           3     0.634090
10         8           2     0.560567
11         8           3     0.439433
12         3           2     0.437765
13         3           3     0.562235
14         1           2     0.373314
15         1           3     0.626686
16         7           2     0.433347
17         7           3     0.566653
18         0           2     0.415010
19         0           3     0.584990

# 3. Continued, how much pre-spikes and post-spikes for the spike?

In [8]:
def get_pre_post_spike(cluster, spike_count):
    cluster_df_12 = pd.read_csv(f'../../Data_processed/statistics/{spike_count}spike_12_clusters.csv')
    cluster_df_13 = pd.read_csv(f'../../Data_processed/statistics/{spike_count}spike_13_clusters.csv')
    cluster_df_24 = pd.read_csv(f'../../Data_processed/statistics/{spike_count}spike_24_clusters.csv')
    cluster_df_34 = pd.read_csv(f'../../Data_processed/statistics/{spike_count}spike_34_clusters.csv')
    cluster_df_12 = cluster_df_12[cluster_df_12['cluster'] == cluster]
    cluster_df_13 = cluster_df_13[cluster_df_13['cluster'] == cluster]
    cluster_df_24 = cluster_df_24[cluster_df_24['cluster'] == cluster]
    cluster_df_34 = cluster_df_34[cluster_df_34['cluster'] == cluster]
    spike_12 = np.random.choice(cluster_df_12['count_1s_before_2'], p=cluster_df_12['probability'])
    spike_13 = np.random.choice(cluster_df_13['count_1s_before_3'], p=cluster_df_13['probability'])
    spike_24 = np.random.choice(cluster_df_24['count_4s_after_2'], p=cluster_df_24['probability'])
    spike_34 = np.random.choice(cluster_df_34['count_4s_after_3'], p=cluster_df_34['probability'])
    return spike_12, spike_13, spike_24, spike_34

prespike_2, prespike_3, postspike_2, postspike_3 = get_pre_post_spike(cluster, spike_count)
print(prespike_2, prespike_3, postspike_2, postspike_3)

2 2 2 1

In [16]:
cluster_df_12 = pd.read_csv(f'../../Data_processed/statistics/{spike_count}spike_12_clusters.csv')
cluster_df_12

    count_1s_before_2  probability  cluster
0                   1     0.602467        6
1                   2     0.215901        6
2                   3     0.074023        6
3                   4     0.047293        6
4                   5     0.033585        6
..                ...          ...      ...
65                  3     0.083650        0
66                  4     0.043515        0
67                  5     0.026193        0
68                  6     0.015716        0
69                  7     0.009294        0

[70 rows x 3 columns]

# 4. The magnitude for the spikes

In [9]:
def get_spike_magnitude(spike_type, cluster, mean, std, max):
    count = len(spike_type)
    spike_mag_stats_df = pd.read_csv('../../Data_processed/statistics/spike_mag_stats.csv')
    spike_mag_stats_df = spike_mag_stats_df[spike_mag_stats_df['clusters'] == cluster]

    spike_mag = []
    for type in spike_type:

        if type == 2:
            min_mag = mean + 2*std
            max_mag = mean + 3*std
        else:
            min_mag = mean + 3*std
            max_mag = max
        
        temp_df = spike_mag_stats_df[spike_mag_stats_df['spike_type'] == type]
        mag = np.random.normal(temp_df['mean'], temp_df['std'])
        while mag < min_mag or mag > max_mag:
            mag = np.random.normal(temp_df['mean'], temp_df['std'])
        spike_mag.append(mag[0])
    return spike_mag

spike_mag = get_spike_magnitude(spike_type, cluster, mean, std, max)
print(spike_mag)

[0.37796821999157215, 0.43952745967647555]

In [17]:
spike_mag_stats_df = pd.read_csv('../../Data_processed/statistics/spike_mag_stats.csv')
spike_mag_stats_df

    clusters  spike_type      mean       std
0          6           2  3.508792  0.680900
1          6           3  5.467586  1.945298
2          9           2  3.401628  0.830055
3          9           3  5.566434  2.626187
4          2           2  3.811648  0.738265
5          2           3  6.635555  2.592647
6          5           2  3.409268  0.663323
7          5           3  5.441601  1.976626
8          4           2  3.440811  0.749854
9          4           3  6.109367  2.953351
10         8           2  3.445390  0.763317
11         8           3  5.271655  1.920465
12         3           2  3.059832  0.739677
13         3           3  5.974188  3.182274
14         1           2  3.222048  0.772998
15         1           3  6.003639  2.750977
16         7           2  3.004617  0.603697
17         7           3  4.729786  1.673692
18         0           2  3.648116  0.671629
19         0           3  5.991810  2.378078

# All Together

In [10]:
def get_spike_df(cluster, month, mean, std, max):
    spike_df = pd.DataFrame()
    spike_df['time'] = pd.date_range('00:00:00', '23:30:00', freq='30T')
    spike_df['time'] = spike_df['time'].dt.time
    spike_df['spike_type'] = 0
    spike_df['spike_magnitude'] = 1

    spike_count = generate_random_spike_count(cluster, month)
    spike_time = get_spike_time(cluster, spike_count)
    # Turn the spike time into a list
    if spike_count == 1:
        spike_time = [spike_time]
    else:
        spike_time = list(spike_time)
    spike_time = [pd.to_datetime(time).time() for time in spike_time]
    spike_type = get_spike_type(cluster, spike_count)
    spike_mag = get_spike_magnitude(spike_type, cluster, mean, std, max)

    prespike_2, prespike_3, postspike_2, postspike_3 = get_pre_post_spike(cluster, spike_count)

    for i in range(spike_count):
        spike_df.loc[spike_df['time'].isin(spike_time), 'spike_type'] = spike_type[i]
        spike_df.loc[spike_df['time'] == spike_time[i], 'spike_magnitude'] = spike_mag[i]

    for i, time in enumerate(spike_time):
        spike_index = spike_df.index[spike_df['time'] == time].tolist()[0]  # Get the index of the current spike time
        
        # Pre-Spike Logic
        pre_spike_marker = 1 if spike_type[i] == 2 else (1 if spike_type[i] == 3 else None)
        pre_spike_count = prespike_2 if spike_type[i] == 2 else (prespike_3 if spike_type[i] == 3 else 0)
        
        # Post-Spike Logic
        post_spike_marker = 4 if spike_type[i] == 2 else (4 if spike_type[i] == 3 else None)
        post_spike_count = postspike_2 if spike_type[i] == 2 else (postspike_3 if spike_type[i] == 3 else 0)
        
        # Update DataFrame for Pre-Spike
        for j in range(1, pre_spike_count + 1):
            if spike_index - j >= 0 and spike_df.at[spike_index - j, 'spike_type'] == 0:  # Ensure index does not go negative
                spike_df.at[spike_index - j, 'spike_type'] = pre_spike_marker
        
        # Update DataFrame for Post-Spike
        for j in range(1, post_spike_count + 1):
            if spike_index + j < len(spike_df) and spike_df.at[spike_index + j, 'spike_type'] == 0:  # Ensure index does not exceed DataFrame length
                spike_df.at[spike_index + j, 'spike_type'] = post_spike_marker
    spike_df = pd.DataFrame(spike_df)
    return spike_df

spike_df = get_spike_df(cluster, 2, mean, std, max)
spike_df

        time  spike_type  spike_magnitude
0   00:00:00           0         1.000000
1   00:30:00           0         1.000000
2   01:00:00           0         1.000000
3   01:30:00           0         1.000000
4   02:00:00           0         1.000000
5   02:30:00           0         1.000000
6   03:00:00           0         1.000000
7   03:30:00           0         1.000000
8   04:00:00           0         1.000000
9   04:30:00           0         1.000000
10  05:00:00           0         1.000000
11  05:30:00           0         1.000000
12  06:00:00           0         1.000000
13  06:30:00           1         1.000000
14  07:00:00           1         1.000000
15  07:30:00           1         1.000000
16  08:00:00           1         1.000000
17  08:30:00           1         1.000000
18  09:00:00           2         0.400311
19  09:30:00           4         1.000000
20  10:00:00           1         1.000000
21  10:30:00           2         1.001719
22  11:00:00           4         1.000000
23  11:30:00           0         1.000000
24  12:00:00           0         1.000000
25  12:30:00           0         1.000000
26  13:00:00           0         1.000000
27  13:30:00           0         1.000000
28  14:00:00           0         1.000000
29  14:30:00           0         1.000000
30  15:00:00           1         1.000000
31  15:30:00           1         1.000000
32  16:00:00           1         1.000000
33  16:30:00           1         1.000000
34  17:00:00           1         1.000000
35  17:30:00           2         0.407832
36  18:00:00           4         1.000000
37  18:30:00           0         1.000000
38  19:00:00           0         1.000000
39  19:30:00           0         1.000000
40  20:00:00           0         1.000000
41  20:30:00           0         1.000000
42  21:00:00           0         1.000000
43  21:30:00           0         1.000000
44  22:00:00           0         1.000000
45  22:30:00           0         1.000000
46  23:00:00           0         1.000000
47  23:30:00           0         1.000000

In [11]:
import utils
utils.get_48_spike_data()

     time  spike_type  spike_magnitude
0   00:00           0         1.000000
1   00:30           0         1.000000
2   01:00           1         1.000000
3   01:30           1         1.000000
4   02:00           1         1.000000
5   02:30           2         4.077471
6   03:00           4         1.000000
7   03:30           0         1.000000
8   04:00           0         1.000000
9   04:30           0         1.000000
10  05:00           0         1.000000
11  05:30           0         1.000000
12  06:00           0         1.000000
13  06:30           0         1.000000
14  07:00           0         1.000000
15  07:30           0         1.000000
16  08:00           0         1.000000
17  08:30           0         1.000000
18  09:00           0         1.000000
19  09:30           0         1.000000
20  10:00           0         1.000000
21  10:30           0         1.000000
22  11:00           0         1.000000
23  11:30           1         1.000000
24  12:00           1         1.000000
25  12:30           1         1.000000
26  13:00           2         4.077471
27  13:30           4         1.000000
28  14:00           0         1.000000
29  14:30           0         1.000000
30  15:00           0         1.000000
31  15:30           0         1.000000
32  16:00           0         1.000000
33  16:30           0         1.000000
34  17:00           0         1.000000
35  17:30           0         1.000000
36  18:00           1         1.000000
37  18:30           1         1.000000
38  19:00           1         1.000000
39  19:30           2         4.077471
40  20:00           4         1.000000
41  20:30           0         1.000000
42  21:00           0         1.000000
43  21:30           0         1.000000
44  22:00           0         1.000000
45  22:30           0         1.000000
46  23:00           0         1.000000
47  23:30           0         1.000000